### ISSUE TITLE
Update Tizen version that is downloaded?

### ISSUE THREAD

**Issue by Qqwy** [Toxblh/tizen-studio-arch#2]
This guide/install script worked fine. However, currently we are on Tizen version 4.1.1, and `install.sh` still installs version 3.7.
This might be worth updating.

Thank you for this helper script!

**Comment by SolAZDev** [comment]
You could technically update it by changing line 3 to `https://download.tizen.org/sdk/Installer/tizen-studio_4.1.1/web-ide_Tizen_Studio_4.1.1_ubuntu-64.bin`
But I agree, it should be updated.

**Comment by Toxblh** [comment]
Thank you, guys!
