### ISSUE TITLE
Some java windows with bad sizes

### ISSUE THREAD

**Issue by aleixq** [Toxblh/tizen-studio-arch#6]
Some problems with kwin while running device manager, such as some windows not well sized (1 pixel x 59) so is impossible to connect to devices. 
To solve it change to other than kde wm  or force windows size as in https://ahelpme.com/software/kde-plasma/kde-plasma-windows-force-resize-ikvm-virtual-keyboard/

**Comment by Toxblh** [comment]
Thank you for the info
